channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =8.1.1
- pyiron_base =0.6.9
- pyiron_atomistics =0.3.7
- numpy =1.26.2
- pandas =2.1.3
- matplotlib-base =3.8.2
- nbconvert =7.11.0
- nbformat =5.9.2
