channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =8.0.6
- pyiron_base =0.5.38
- pyiron_atomistics =0.2.67
- numpy =1.24.3
- pandas =2.0.1
- matplotlib-base =3.7.1
- nbconvert =7.4.0
- nbformat =5.8.0
