channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.6.5
- pyiron_base =0.5.0
- pyiron_atomistics =0.2.33
- numpy =1.22.0
- pandas =1.3.5
- matplotlib-base =3.5.1
