channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.7.0
- pyiron_base =0.5.12
- pyiron_atomistics =0.2.45
- numpy =1.22.3
- pandas =1.4.2
- matplotlib-base =3.5.1
