channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.6.5
- pyiron_base =0.4.3
- pyiron_atomistics =0.2.33
- numpy =1.21.4
- pandas =1.3.5
- matplotlib-base =3.5.1
