channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - ipywidgets =7.6.3
  - pyiron_base =0.2.17
  - pyiron_atomistics =0.2.17
  - numpy =1.21.0
  - pandas =1.3.0
  - matplotlib-base =3.4.2
