channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.7.1
- pyiron_base =0.5.24
- pyiron_atomistics =0.2.57
- numpy =1.23.3
- pandas =1.5.0
- matplotlib-base =3.6.0
