channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.6.3
- pyiron_base =0.2.20
- pyiron_atomistics =0.2.20
- numpy =1.21.1
- pandas =1.3.0
- matplotlib-base =3.4.2
