channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.6.5
- pyiron_base =0.3.8
- pyiron_atomistics =0.2.27
- numpy =1.21.3
- pandas =1.3.4
- matplotlib-base =3.4.3
