channels:
  - conda-forge
dependencies:
  - coveralls
  - coverage
  - codacy-coverage
  - ipywidgets =7.6.3
  - pyiron_base =0.2.9
  - pyiron_atomistics =0.2.10
  - numpy =1.20.2
  - pandas =1.2.4
  - matplotlib-base =3.4.1