channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.6.3
- pyiron_base =0.2.22
- pyiron_atomistics =0.2.21
- numpy =1.21.1
- pandas =1.3.1
- matplotlib-base =3.4.2
