channels:
- conda-forge
dependencies:
- coverage
- codacy-coverage
- ipywidgets =8.1.5
- pyiron_base =0.10.9
- pyiron_atomistics =0.6.18
- maggma =0.60.2
- numpy =1.26.4
- pandas =2.2.3
- matplotlib-base =3.10.0
- nbconvert =7.16.4
- nbformat =5.10.4
