channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =8.0.6
- pyiron_base =0.5.35
- pyiron_atomistics =0.2.65
- numpy =1.24.2
- pandas =2.0.0
- matplotlib-base =3.7.1
