channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.7.1
- pyiron_base =0.5.35
- pyiron_atomistics =0.2.62
- numpy =1.24.2
- pandas =2.0.0
- matplotlib-base =3.6.3
