channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.6.5
- pyiron_base =0.3.10
- pyiron_atomistics =0.2.29
- numpy =1.21.4
- pandas =1.3.4
- matplotlib-base =3.5.0
