channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.7.0
- pyiron_base =0.5.13
- pyiron_atomistics =0.2.47
- numpy =1.23.0
- pandas =1.4.2
- matplotlib-base =3.5.2
