channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.7.1
- pyiron_base =0.5.21
- pyiron_atomistics =0.2.54
- numpy =1.23.1
- pandas =1.4.3
- matplotlib-base =3.5.2
