channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- ipywidgets =7.7.1
- pyiron_base =0.5.28
- pyiron_atomistics =0.2.59
- numpy =1.23.5
- pandas =1.5.1
- matplotlib-base =3.6.2
